CREATE TABLE IF NOT EXISTS worker (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(1000) NOT NULL CHECK (LENGTH(NAME) BETWEEN 1 AND 1001),
    BIRTHDAY DATE CHECK (BIRTHDAY >= '1900-01-01'),
    LEVEL VARCHAR(10) NOT NULL,
    SALARY INT CHECK (SALARY BETWEEN 100 AND 100000),
    CONSTRAINT chk_level 
        CHECK (LEVEL IN ('Trainee', 'Junior', 'Middle', 'Senior'))
);

CREATE TABLE IF NOT EXISTS client (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR NOT NULL CHECK (LENGTH(NAME) BETWEEN 1 AND 1001)
);

CREATE TABLE IF NOT EXISTS project (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR NOT NULL CHECK (LENGTH(NAME) BETWEEN 1 AND 1001),
    CLIENT_ID INT NOT NULL,
    FOREIGN KEY(CLIENT_ID) REFERENCES client(ID),
    START_DATE DATE CHECK (START_DATE >= '1900-01-01'),
    FINISH_DATE DATE CHECK (FINISH_DATE >= '1900-01-01')
);

CREATE TABLE IF NOT EXISTS project_worker (
    PROJECT_ID INT NOT NULL,
    WORKER_ID INT NOT NULL,
    PRIMARY KEY (PROJECT_ID, WORKER_ID),
    FOREIGN KEY (PROJECT_ID) REFERENCES project(ID),
    FOREIGN KEY (WORKER_ID) REFERENCES worker(ID)
);
